
--Table Creation
create table user_customer (
id int primary key,
username varchar,
dob Date,
nationality varchar,
race varchar
);

--Here's the sample records to use to populate your new table.
--
--| id | username        | DOB        | Nationality  | Race       |
--|----|-----------------|------------|--------------|------------|
--| 1  | user123456      | 1990-05-15 | USA          | Caucasian  |
--| 2  | john_doe123     | 1985-08-22 | Canada       | African    |
--| 3  | cool_cat        | 1992-03-10 | UK           | Asian      |
--| 4  | sara_loves_cats | 1988-11-28 | Australia    | Hispanic   |
--| 5  | traveler2022    | 1996-07-05 | Germany      | Native     |
--| 6  | coding_ninja    | 1994-02-18 | France       | Caucasian  |
--| 7  | coffee_lover    | 1982-09-12 | Brazil       | African    |
--| 8  | beach_bum       | 1993-04-30 | Mexico       | Hispanic   |
--| 9  | nature_guru     | 1987-12-03 | Japan        | Asian      |
--| 10 | music_maniac    | 1998-06-20 | South Korea  | Asian      |

insert into user_customer(id, username, dob, nationality, race)
values (1, 'user123456', '1990-05-15', 'USA', 'Caucasian');

insert into user_customer(id, username, dob, nationality, race)
values (2, 'john_doe123', '1985-08-22', 'Canada', 'African');

insert into user_customer(id, username, dob, nationality, race)
values (2, 'cool_cat', '1992-03-10', 'UK', 'Asian');

insert into user_customer(id, username, dob, nationality, race)
values (2, 'sara_loves_cats', '1988-11-28', 'Australia', 'Hispanic');

insert into user_customer(id, username, dob, nationality, race)
values (2, 'traveler2022', '1996-07-05', 'Germany', 'Native');

insert into user_customer(id, username, dob, nationality, race)
values (2, 'coding_ninja', '1994-02-18', 'France', 'Caucasian');

insert into user_customer(id, username, dob, nationality, race)
values (2, 'coffee_lover', '1982-09-12', 'Brazil', 'African');

insert into user_customer(id, username, dob, nationality, race)
values (2, 'beach_bum', '1993-04-30', 'Mexico', 'Hispanic');

insert into user_customer(id, username, dob, nationality, race)
values (2, 'nature_guru', '1987-12-03', 'Japan', 'Asian');

insert into user_customer(id, username, dob, nationality, race)
values (2, 'music_maniac', '1998-06-20', 'South Korea', 'Asian');

create table user_forgot_passw_reqs(
id int primary key generated by default as identity,
user_id int,
hash varchar,
created_dtm timestamp,
expiration timestamp,
constraint user_id_fk foreign key(user_id) references user_customer(id)
);